//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubovskiy_TelephoneGuide
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Городской_Телефонный_СправочникEntities : DbContext
    {
        public Городской_Телефонный_СправочникEntities()
            : base("name=Городской_Телефонный_СправочникEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
        public static Городской_Телефонный_СправочникEntities GetDatabase1()
        {
            Городской_Телефонный_СправочникEntities content = new Городской_Телефонный_СправочникEntities();
            return content;
        }
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        //internal static Городской_Телефонный_СправочникEntities GetDatabase1()
        //{
        //    throw new NotImplementedException();
        //}

        public virtual DbSet<Abonent> Abonents { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
    }
}
