//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dubovskiy_TelephoneGuide
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        public int AbIndex { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public int AddIndex { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> OrgIndex { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
